CREATE TABLE raw_data_schema.raw_orders_data (
    id BIGSERIAL PRIMARY KEY,
    invoice_no VARCHAR(255),
    date TIMESTAMP,
    timestamp TIMESTAMP,
    payment_type VARCHAR(255),
    order_type VARCHAR(255),
    area VARCHAR(255),
    sub_order_type VARCHAR(255),
    phone VARCHAR(255),
    name VARCHAR(255),
    address VARCHAR(255),
    my_amount NUMERIC(38,2),
    discount NUMERIC(38,2),
    net_sales NUMERIC(38,2),
    container_charge NUMERIC(38,2),
    total_tax NUMERIC(38,2),
    round_off NUMERIC(38,2),
    total_amount NUMERIC(38,2),
    online_tax_calculated NUMERIC(38,2),
    gst_paid_by_ecommerce NUMERIC(38,2),
    amount_cgst NUMERIC(38,2),
    cgst NUMERIC(38,2),
    amount_sgst NUMERIC(38,2),
    sgst NUMERIC(38,2),
    raw_line TEXT
);