package com.cloudkitchen;

/**
 * This is a placeholder class, typically generated by Maven.
 * It is not actively used by the Spring Boot application.
 * The actual application entry point is `DataIngestionServiceApplication.java`.
 */
public class App 
{
    /**
     * Main method for the placeholder class.
     * @param args Command line arguments.
     */
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
    }
}
